export default {
    id: '1',
    name: 'Mood.',
    by: 'Spotify',
    numberOfLikes: 30,
    imageUri: 'https://imgs.capitalfm.com/images/254365?crop=16_9&width=660&relax=1&signature=HwbA-DKlZAgbrSBHqyCJAUd2SeY=',
    artistsHeadline: 'Taylor Swift, Kygo Objective C, Avicii',
    duration: '1h 37m',
    songs: [
        {
            id: '1',
            imageUri: 'https://i.scdn.co/image/ab67616d0000b273e6c40bd47002f3faffb31ebe',
            title: 'Take my Breath',
            artist: 'The Weeknd',
            duration: '1m 20s',
        },
        {
            id: '2',
            imageUri: 'https://i.ytimg.com/vi/cPJUBQd-PNM/hqdefault.jpg',
            title: 'Revenge',
            artist: 'CaptainSparklez',
            duration: '1m 20s',
        },
        {
            id: '3',
            imageUri: 'https://media.pitchfork.com/photos/608839f84c67840074db8afb/1:1/w_600/Billie-Eilish-Happier-Than-Ever.jpeg',
            title: 'Happier than Ever',
            artist: 'Billie Eilish',
            duration: '1m 20s',
        },
        {
            id: '4',
            imageUri: 'https://upload.wikimedia.org/wikipedia/en/b/b2/Olivia_Rodrigo_-_SOUR.png',
            title: 'good 4 u',
            artist: 'Olivia Rodrigo',
            duration: '1m 20s',
        },
        {
            id: '5',
            imageUri: 'https://i.scdn.co/image/ab67616d0000b273e6c40bd47002f3faffb31ebe',
            title: 'Take my Breath',
            artist: 'The Weeknd',
            duration: '1m 20s',
        },
        {
            id: '6',
            imageUri: 'https://i.ytimg.com/vi/cPJUBQd-PNM/hqdefault.jpg',
            title: 'Revenge',
            artist: 'CaptainSparklez',
            duration: '1m 20s',
        },
        {
            id: '7',
            imageUri: 'https://media.pitchfork.com/photos/608839f84c67840074db8afb/1:1/w_600/Billie-Eilish-Happier-Than-Ever.jpeg',
            title: 'Happier than Ever',
            artist: 'Billie Eilish',
            duration: '1m 20s',
        },
        {
            id: '8',
            imageUri: 'https://upload.wikimedia.org/wikipedia/en/b/b2/Olivia_Rodrigo_-_SOUR.png',
            title: 'good 4 u',
            artist: 'Olivia Rodrigo',
            duration: '1m 20s',
        },
        {
            id: '9',
            imageUri: 'https://i.scdn.co/image/ab67616d0000b273e6c40bd47002f3faffb31ebe',
            title: 'Take my Breath',
            artist: 'The Weeknd',
            duration: '1m 20s',
        },
        {
            id: '10',
            imageUri: 'https://i.ytimg.com/vi/cPJUBQd-PNM/hqdefault.jpg',
            title: 'Revenge',
            artist: 'CaptainSparklez',
            duration: '1m 20s',
        },
        {
            id: '11',
            imageUri: 'https://media.pitchfork.com/photos/608839f84c67840074db8afb/1:1/w_600/Billie-Eilish-Happier-Than-Ever.jpeg',
            title: 'Happier than Ever',
            artist: 'Billie Eilish',
            duration: '1m 20s',
        },
        {
            id: '12',
            imageUri: 'https://upload.wikimedia.org/wikipedia/en/b/b2/Olivia_Rodrigo_-_SOUR.png',
            title: 'good 4 u',
            artist: 'Olivia Rodrigo',
            duration: '1m 20s',
        },
        {
            id: '13',
            imageUri: 'https://i.scdn.co/image/ab67616d0000b273e6c40bd47002f3faffb31ebe',
            title: 'Take my Breath',
            artist: 'The Weeknd',
            duration: '1m 20s',
        },
        {
            id: '14',
            imageUri: 'https://i.ytimg.com/vi/cPJUBQd-PNM/hqdefault.jpg',
            title: 'Revenge',
            artist: 'CaptainSparklez',
            duration: '1m 20s',
        },
        {
            id: '15',
            imageUri: 'https://media.pitchfork.com/photos/608839f84c67840074db8afb/1:1/w_600/Billie-Eilish-Happier-Than-Ever.jpeg',
            title: 'Happier than Ever',
            artist: 'Billie Eilish',
            duration: '1m 20s',
        },
        {
            id: '16',
            imageUri: 'https://upload.wikimedia.org/wikipedia/en/b/b2/Olivia_Rodrigo_-_SOUR.png',
            title: 'good 4 u',
            artist: 'Olivia Rodrigo',
            duration: '1m 20s',
        },
    ]
}